BIPT-31: As a user and a proposer, I will be able to click the pencil button to edit my proposal
aj-may/eybc-bip pull request #26
Opened 2022-12-07 16:24 UTC by KaceyWood8

### Related Ticket

<https://eyblockchain.atlassian.net/jira/software/projects/BIPT/boards/301?selectedIssue=BIPT-31>

#### Dependent PR's

NA

### Description

Edit Icons were added to each draft proposal in the drafts page. The edit icon routes the user to an updateDraft form that populates all fields for that given draft. A user may update any field as desired. The save button saves all updates for that given draft.  

<img width="1261" alt="image" src="https://user-images.githubusercontent.com/104782237/206233125-bea676d1-9d3a-467d-9fbf-ef4a45a6b24b.png">

### QA Instructions
- [ ] clone repo
- [ ] npm i
- [ ] git checkout kinj/lana/kace/bipt-31
- [ ] npm run dev
- [ ] navigate to localhost:3000 in browser

### Checklist

- [x] I have reviewed the code changes myself
- [x] My code meets all of the acceptance criteria of the ticket it closes.
- [x] I have removed unused code (e.g., `console.logs`, commented out blocks, etc.)
- [ ] I have made all necessary changes to the documentation. - no changes needed
- [ ] I have added tests to cover my changes. - no tests for this ticket yet
- [ ] All new and existing tests passed. - no tests for this ticket yet
- [x] Any dependent changes have been merged and published.
- [x] Check PR title name is correct.

2022-12-07 16:30 UTC, meaghanfitzgerald commented
@aj-may pls hit the magic button 😁

2023-01-03 22:30 UTC, abdulmalik97 commented on components/UpdateDraft.tsx
> +import moment from "moment";
We aren't using moment throughout the application. Might as well remove it completely? It makes the app heavy as moment has a large codebase.

2023-01-04 00:02 UTC, meaghanfitzgerald requested changes
once comments are addressed, everything should be good to merge.

2023-01-05 21:41 UTC, abdulmalik97 approved these changes

2023-01-05 21:59 UTC, meaghanfitzgerald approved these changes
lgtm

2023-01-05 21:59 UTC, merged