Adding a "Submit for RFC" button
aj-may/eybc-bip pull request #4
Opened 2022-10-05 14:49 UTC by Lana-Butorovic

I have added a Submit for RFC button to our /new page.

As we don't have an RFC page built out yet, I could not add the routing here. We should add that as a subtask to BIPT23 (that talks about the RFC page).  

I am adding a screenshot below of what the button looks like on the page:

<img width="1219" alt="Screen Shot 2022-10-05 at 10 48 34 AM" src="https://user-images.githubusercontent.com/109984701/194090711-829f367c-48de-4051-9b11-46eab21fdae9.png">

2022-10-06 23:04 UTC, nagrawal3 requested changes

2022-10-06 23:04 UTC, nagrawal3 commented on components/proposalForm.tsx
> +          </Link>
can you run linting on this before pushing, alignment doesn't seem correct

2022-10-07 11:32 UTC, Lana-Butorovic commented on components/proposalForm.tsx
> +          </Link>
Yes, done - thank you for pointing this out

2022-10-10 23:07 UTC, nagrawal3 approved these changes

2022-10-10 23:07 UTC, merged

2022-10-11 12:23 UTC, meaghanfitzgerald commented
@Lana-Butorovic @nagrawal3 This needs to be refactored. The `isLoading` being used here is the same hook as the "Save" button, so when 1 button is pressed, both buttons show the spinning animation as if they had been clicked in unison.