BIPT-32
aj-may/eybc-bip pull request #5
Opened 2022-10-05 21:31 UTC by KaceyWood8

### Related Ticket

[<[https://eyblockchain.atlassian.net/browse/__TICKET__>](https://eyblockchain.atlassian.net/browse/__TICKET__%3E)](https://eyblockchain.atlassian.net/browse/BIPT-32)

### Description

Once clicked on ‘New Proposal’, the user should be navigated to the New Proposal page with the additional required fields:

- BIP # (auto generated)
- Title of BIP
- Author
- Date Proposed (auto generated)
- Date Ratified
- Championship Team (volunteers helping support) (optional)
- Leadership Sponsor (dropdown with partner/SM options)
- Simple Summary/Abstract
- Motivation(s)
- Specifications
- Risks/Impediments
- Success Metrics
- Status (Draft, RFC, Voting, Accepted, Rejected)

![image](https://user-images.githubusercontent.com/104782237/194166682-ba76fad9-0f10-4e61-a4fc-8042dfcd620b.png)

### QA Instructions
- [ ] Step 1: git clone https://github.com/KaceyWood8/eybc-bip.git
- [ ] Step 2: npm i
- [ ] Step 3: View updated files: "src/components/proposalForm.tsx", and "node/modules/.prisma/client/index.d.ts"
- [ ] Step 4: npm run dev
- [ ] Step 5: Open http://localhost:3000/ with your browser to see the result.
- [ ] Step 6: Connect Metamask wallet to log in
- [ ] Step 7: Click on "New Proposal" in top right hand corner of screen.

2022-10-05 22:34 UTC, meaghanfitzgerald commented
Why are `Championship Team` and `Date Proposed` not required fields?

2022-10-05 22:39 UTC, KaceyWood8 commented
@meaghanfitzgerald In BIPT-3 ticket it shows Championship Team in the bullets as optional. For Date Proposed, I assumed it would be optional in case someone wants to save it as draft (Also assumed once it is autogenerated it wouldn't need it to be required since the current date would be filled. No action required from the user for that field)

2022-10-06 23:24 UTC, nagrawal3 requested changes

2022-10-06 23:24 UTC, nagrawal3 commented on components/proposalForm.tsx
> +            <option value="option10">Kartheek Solipuram</option>
use this as an environment variable. Reason: if in the future we have to modify the list, we will not need to make changes to the code, only the environment variable needed to be changed.

2022-10-06 23:24 UTC, nagrawal3 commented on example.env.local
> -# Copy this file and rename to .env.local
leave this file here, do not delete

2022-10-16 19:24 UTC, KaceyWood8 commented on components/proposalForm.tsx
> +            <option value="option10">Kartheek Solipuram</option>
Hi @nagrawal3 I have added this to my latest commit. You can find it in fixtures/practiceleaders/tsx. Please let me know if there is a better way of doing this. Happy to connect online for any updates!

2022-10-16 19:24 UTC, KaceyWood8 commented on example.env.local
> -# Copy this file and rename to .env.local
@nagrawal3 Added file back in latest commit.

2022-10-18 21:33 UTC, nagrawal3 approved these changes

2022-10-18 21:56 UTC, merged