feat: Drafts page implementation
aj-may/eybc-bip pull request #6
Opened 2022-10-11 04:47 UTC by meaghanfitzgerald

### Related Ticket

https://eyblockchain.atlassian.net/browse/BIPT-42

### Description

Created a lazy implementation using a similar schema to the currently existing "All" page. I submit this PR so I can unblock the development of other features (via api implementation) but with full intentions to refactor most of front-end code into more concise, reusable components in the future. 

### QA Instructions

-[ ] checkout to `meag/draft-page-refactor`
-[ ] npm run dev
-[ ] toggle between the `All` and `Drafts` tabs to see the filtered vs. non-filtered pages

### Checklist

- [x] I have reviewed the code changes myself
- [x] I have removed unused code (e.g., `console.logs`, commented out blocks, etc.)
- [x] I have made all necessary changes to the documentation.
- [x] Any dependent changes have been merged and published.
- [x] Checked my PR title name is correct.

2022-10-18 00:03 UTC, nagrawal3 requested changes

2022-10-18 00:03 UTC, nagrawal3 commented on pages/api/drafts/index.ts
> +  const { method, body } = req;
```suggestion
  const { method } = req;
```

2022-10-18 00:03 UTC, nagrawal3 commented on pages/api/drafts/index.ts
> +      const drafts = await prisma.proposal.findMany({
do we have error handling in place? what happens where db query throws error?

2022-10-18 00:03 UTC, nagrawal3 commented on pages/api/drafts/index.ts
> +    case "GET":
maybe add a default case as well which returns 404 error

2022-10-18 17:09 UTC, aj-may commented on pages/api/drafts/index.ts
> +    case "GET":
or `405 Method Not Allowed`

2022-10-20 02:17 UTC, meaghanfitzgerald commented on pages/api/drafts/index.ts
> +  const { method, body } = req;
resolved

2022-10-20 02:24 UTC, meaghanfitzgerald commented on pages/api/drafts/index.ts
> +    case "GET":
had trouble implementing a default case without a valid variable, implemented error handling for the get method. In a future PR i may remove the `draft` endpoint and just write all the gets through the `proposal` endpoint.

2022-10-21 18:40 UTC, nagrawal3 requested changes

2022-10-21 18:40 UTC, nagrawal3 commented on package.json
> +    "@prisma/client": "^4.4.0",
when you are bumping version in `package.json` file, there should be changes in `package-lock.json` file. Can you please commit that as well

2022-10-21 18:40 UTC, nagrawal3 commented on pages/api/proposals/index.ts
>        return res.json(proposals);
```suggestion
      try {
        const proposals = await prisma.proposal.findMany();
        return res.json(proposals);
      } catch (err) {
        return res.status(500).json({
          error: "Error getting proposals",
        });
      }
```

2022-10-21 18:40 UTC, nagrawal3 commented on pages/api/proposals/index.ts
>        return res.json(proposals);
similar changes to other route as well

2022-10-21 18:40 UTC, nagrawal3 commented on pages/api/drafts/index.ts
> +  }
```suggestion
  switch (method) {
    case "GET":
      try {
        const drafts = await prisma.proposal.findMany({
          where: { status: "DRAFT" },
        });
        return res.json(drafts);
      } catch(err) {
        return res.status(500).json({
          error: "Failed to get proposals",
        });
      }
      
    case default:
      return res.status(404).json({
        error: "No such route present",
      });
  }
```

2022-10-21 18:46 UTC, meaghanfitzgerald commented on package.json
> +    "@prisma/client": "^4.4.0",
resolved

2022-10-21 19:01 UTC, nagrawal3 commented on pages/api/drafts/index.ts
> +      });
```suggestion
      return res.status(405).json({
        error: "Method Not Allowed",
      });
```

2022-10-21 19:05 UTC, nagrawal3 approved these changes

2022-10-21 19:06 UTC, merged